import os
from environs import Env

env = Env()
env.read_env()

KEYCLOAK_ISSUER = env.str('KEYCLOAK_ISSUER')
KEYCLOAK_CLIENT_ID = env.str('KEYCLOAK_CLIENT_ID')
KEYCLOAK_CLIENT_SECRET = env.str('KEYCLOAK_CLIENT_SECRET')
KEYCLOAK_AUDIENCE = env.str('KEYCLOAK_AUDIENCE')

CDIP_API_ENDPOINT = env.str('CDIP_API_ENDPOINT')
CDIP_ADMIN_ENDPOINT = env.str('CDIP_ADMIN_ENDPOINT')
CDIP_INTEGRATION_TYPE_SLUG = env.str('CDIP_INTEGRATION_TYPE_SLUG')

METRICS_PROXY_HOST = env.str('METRICS_PROXY_HOST')
METRICS_PROXY_PORT = env.int('METRICS_PROXY_PORT', 8125)
METRICS_PREFIX = CDIP_INTEGRATION_TYPE_SLUG
LOG_LEVEL = env.log_level('LOG_LEVEL', 'INFO')

RUNNING_IN_K8S = bool('KUBERNETES_PORT' in os.environ)

OAUTH_TOKEN_URL = f'{KEYCLOAK_ISSUER}/protocol/openid-connect/token'
PORTAL_API_ENDPOINT = f'{CDIP_ADMIN_ENDPOINT}/api/v1.0'
PORTAL_API_INBOUND_INTEGRATIONS_ENDPOINT = f'{PORTAL_API_ENDPOINT}/integrations/inbound/configurations'
